<section class="sidebar">
    <!-- Use Navigation Here -->
    <ul class="sidebar-menu">
        <!-- DIVIDER -->
        <li class="header">INSTITUTE SERVICES</li>
        <!-- END DIVIDER -->
        <li class="active"><a href="<?php echo $this->url('dashboard'); ?>">
            <i class="fa fa-feed"></i> <span>General Announcements</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-calendar"></i> <span>Class Schedule</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-certificate"></i> <span>Evaluation of Grades</span></a>
        </li>        
        <li><a href="#">
            <i class="fa fa-exclamation-triangle"></i> <span>Clearance Items</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">ACCOUNT MANAGEMENT</li>
        <!-- END DIVIDER -->
        <li><a href="#">
            <i class="fa fa-book"></i> <span>Passbook Transactions</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-gear"></i> <span>Profile Settings</span></a>
        </li>         
    </ul>
</section>